version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/wd
    steps:
      - run:
          name: Versions
          command: |
            echo "node: $(node --version)"
            echo "npm: $(npm --version)"
            echo "yarn: $(yarn --version)"
      - checkout
      - restore_cache:
          keys:
            - v1-{{ .Branch }}
            - v1-master
      - run:
          name: Install dependencies
          command: yarn install --no-lockfile
      - run:
          name: Test
          command: yarn test
      - save_cache:
          key: v1-{{ .Branch }}-{{ epoch }}
          paths:
            - ~/.cache/yarn
