version: 2
jobs:
  build:
    docker:
      - image: node:6
    working_directory: ~/wd
    steps:
      - run:
          name: Versions
          command: |
            npm version
      - checkout
      - restore_cache:
          keys:
            - v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
            - v1-npm-master-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm i
      - run:
          name: Test
          command: npm test
      - save_cache:
          key: v1-npm-{{ .Branch }}-{{ checksum "package.json" }}
          paths:
            - node_modules
